# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 5 # pagination based on number of posts
paginate_path: "/blog/page:num/"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
#disqus: dbyll
#google_analytics: dbyll
title: Sylverfall

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Sylverfall

description: Code, tools & stuff !
author:
  name: Baptiste Gauduchon
  email: baptiste.gauduchon@gmail.com
  github: bgauduch
  twitter: bgauduch
#  pinterest: asd123
  linkedin: baptistegauduchon
  bio: Personal geek & dev stuffs
#  email_md5: 726351295ec82e145928582f595aa3aa

#rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate
